# Generated by Django 3.0.3 on 2020-04-13 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=5)),
                ('cartera', models.CharField(max_length=6)),
                ('clientes', models.CharField(max_length=150)),
                ('fecha_alta', models.CharField(default='', max_length=10)),
                ('saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('vigencia', models.CharField(max_length=30)),
                ('dirigido', models.CharField(max_length=40)),
                ('sublineas', models.CharField(max_length=40)),
                ('restricciones', models.CharField(max_length=200)),
                ('cartera', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='concurso/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('vigencia', models.CharField(max_length=30)),
                ('sublineas', models.CharField(max_length=40)),
                ('dirigido', models.CharField(max_length=40)),
                ('restricciones', models.CharField(max_length=200)),
                ('avances', models.CharField(max_length=100)),
                ('descuento', models.CharField(max_length=20)),
                ('cartera', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='promocion/images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
